### ISSUE TITLE
[BUG]: サーバーアクション使用時にミドルウェアでリダイレクトできない

### ISSUE THREAD

**Issue by P-manBrown** [P-manBrown/tascon-frontend#303]
### 説明

ミドルウェアのリダイレクトでエラーが発生し、リダイレクトできないことがある。

発生条件は以下のとおり。

- リクエストにサーバーアクションを使用している
- 保護されたページ（ログインが必要なページ）のフォームを送信する
- `auth_cookie`クッキーが削除されている

発生するエラーは以下のとおり。

```shell
failed to forward action response TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async rC (/home/node/tascon-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:4216)
    at async rE (/home/node/tascon-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:8094)
    at async r7 (/home/node/tascon-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)
    at async doRender (/home/node/tascon-frontend/node_modules/next/dist/server/base-server.js:1413:30)
    at async cacheEntry.responseCache.get.routeKind (/home/node/tascon-frontend/node_modules/next/dist/server/base-server.js:1574:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/home/node/tascon-frontend/node_modules/next/dist/server/base-server.js:1482:28)
    at async NextNodeServer.renderPageComponent (/home/node/tascon-frontend/node_modules/next/dist/server/base-server.js:1908:24)
    at async NextNodeServer.renderToResponseImpl (/home/node/tascon-frontend/node_modules/next/dist/server/base-server.js:1946:32) {
  [cause]: Error
      at makeNetworkError (node:internal/deps/undici/undici:8968:35)
      at httpRedirectFetch (node:internal/deps/undici/undici:10515:32)
      at httpFetch (node:internal/deps/undici/undici:10475:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async node:internal/deps/undici/undici:10212:20
      at async mainFetch (node:internal/deps/undici/undici:10202:20)
}
```

### 再現手順

1. ログインする
2. `/password/change`にアクセス
3. `auth_cookie`クッキーを削除
4. フォームに値を入力
5. フォームを送信

### 期待される動作

`auth_cookie`クッキーが設定されていない状態で`/password/change`のフォームを送信すると`/login`にリダイレクトされる。

### スクリーンショット

![画面収録 2024-10-24 13 48 21](https://github.com/user-attachments/assets/3d5b13ec-00e9-4679-a4dc-88b6b97441be)

### 環境

- OS: macOS v15.0.1
- ブラウザ: Google Chrome v130.0.6723.70（Official Build） （arm64）

**Comment by P-manBrown** [comment]
Next.js v.15.0.0で修正された可能性あり。

- [Redirect in middleware when request is a server action fails with "failed to forward action response" · vercel/next.js · Discussion #64993](https://v.gd/w1rUA5)
- [update redirect handling on forwarded action requests by ztanner · Pull Request #65097 · vercel/next.js](https://v.gd/mRCf3u)
- [Release v15.0.0 · vercel/next.js](https://v.gd/0imP3a)

**Comment by P-manBrown** [comment]
Due to #354, `auth_cookie` is no longer used, so this issue no longer occurs.
